---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongo-secret
  namespace: default
spec:
  encryptedData:
    mongo-password: AgBhcKtPHrRyBK0IHUjxCiA4HpqmkE3xojs//WfiQkqNR0NN6RVff3W5fLytD1F5pUtnxyxHibdtr26ddjyKyohyiKXMXg9d1ESAOpBR0Tl9B/iCYKoJkLJ+/SXEYxPdUHxoZj9JnJg4GhDhYJNaQqYTiR/5vU7In60zEfefSIBAdQpAmCe8rqVGZOLkdZlJM2oCBa++X8wcSDlf2cJd20Cv098qs1CZ+xtzXJxlbxj55mdj/XR9o39n9xMxHzSZImvcb91tXxU67dfIzot9endnkcqMPTtj418eE4qMUMVosOoVfECElWAyluVU2GNcuOWVrwboP7JvFj3Cnhq/3/oJ9ZCSePS3ir6yy9V7tcU+mwSMLJFpjVt614R/zwLQovqGVCNua+pMOVdVmdhKujtUSzLAcfocX/jcKc/BX6OAevTJ9tAn+GKgVfreD3jrtNArvyAZWFP6Go0v0qjW9aKlU7vnwylS9LCmDQG11Vev19SmiEZ/YVRfdoS5TJwrkAqh/GupC2iJeOqR+h6HXTAPYcDq9Ix08IWiA+SX4iK51leM4iU41gcbDaFCe+aVRVDOyznoPxCS4+6Y1CgQnICbfC3wFVKuOOlHZO0GqkeDI6nFXLBN6zf4jKiF8lFMHSI0SmAPFY/DvqdmYnxYxnXts+kxPoizWhOQUW9aS/0rUHC8VGIBPMNTF4SkIsd82Snc0QiHsP9TDW9GnXur
    mongo-user: AgBZGNHqil53+kpVLoswz7/T/+DM9aQihLXcMD54nUwmA3S8ppI8NkGMlE8ZRI6yUsOkETGGv/EIBs8GVGaBHsWTvdH2Pqrmnq/FF3GeVHptVwmb87gtTNy7xDWC8kOHCFSADlRmNDM2Yw5Rr00U6TN+vvyOu8n+AfvLIMv/kk4Pm2bYugADYB2bwAa/7G0xQ0fT4poTkpMsIlS6SercRnRkALpxHJL+6A9hyfKqbGLgzUNjt231Ni6p7II9FcmcJVgG4k+n72V4mpo2cOFFRNdgu/OiEj4/7/MohxnQu7JJwPEPGfem6OIKCXOSqV6xuBrBDXwtAR4vuamPsoGcD9i7sHc2tP7aMwryWcrTJ5bqmFVd9WDpR0adD91WqwXHqPLIqNXhC2+QR+lmX0gZC+/hsTUIwIRsbzKDxI8yBpLof96d6P/MktWmXq6k/vUoEN8PIhHdKFsOJY1tsaObPTK2nokwhQAakmIG+FqS0rV1I6blxJsPzBoMtLrVRNKk38ONOIvHHg0/5Su4kelLM0eHetrt4+Pb01uEQkDY+7lbjFcAUKdKzFnFghGY7iZnK+WIFBToTE2eRlTaYBOu2YTiXWeY36eQOdoRor62IHIwChDPF5RknuDzlBTIuNwkkArMR5bM4qvwaKZwaU7IdikJBSR7Y9cWf4LpM7FqstJEvECkpuyZ5hTqxeeYz//lLAz5wStvnTXKOLg=
  template:
    metadata:
      creationTimestamp: null
      name: mongo-secret
      namespace: default
    type: Opaque
