apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: default
spec:
  containers:
  - name: test-container
    image: curlimages/curl:latest # Lightweight image with curl installed
    command: ["sleep", "3600"] # Keeps the pod running for testing